# Generated by Django 3.2.6 on 2021-08-11 12:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%y'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 12, 47, 29, 645501, tzinfo=utc)),
        ),
    ]
