# Generated by Django 3.2.6 on 2021-08-11 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210811_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 13, 2, 34, 389779, tzinfo=utc)),
        ),
    ]
